### ISSUE TITLE
Estimates from Day-1 doesn't show in plot

### ISSUE THREAD

**Issue by d0nghyunkang** [dballaelliott/esplot#16]
Hey, I've found another peculiar issue in the resulting plot. The command doesn't show the estimate from Day-1. For example, if I run the following code from your example_csv, the resulting plot omits the estimate from Day-1.

`
esplot paygrade, by(male) event(to_male_mgr, save) window(-20 30) estimate_reference
`

![Graph](https://user-images.githubusercontent.com/55714571/109507611-34411000-7a9f-11eb-85a6-dd8f8aec64f2.png)

**Comment by dballaelliott** [comment]
Hi, 

Thanks for highlighting this, this is actually by design! 

The dynamic treatment effects (or event-study coefficients are only identified [up to a constant](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2826228)). By convention, these coefficients are often normalized to 0 in the time `t = -1.` For example, that's what is done in the figures in [Cullen & Perez-Truglia, 2020](https://www.nber.org/system/files/working_papers/w26530/w26530.pdf). Of course, the normalization is arbitrary, and e.g. [Chetty, Friedman & Rockoff, 2014](http://www.rajchetty.com/chettyfiles/w19423.pdf) normalize with respect to other years (-3 and +2). 

I know that moving the reference period is a feature that has been requested in the past, and I'll flag that as a new feature to add (i.e. changing the omitted period to `t=0` or `t = -2`). 

There is currently an undocumented option called `recenter` that may be of interest to you. It is a workaround for the under-identification of the full set of dynamic effects (i.e. the coefficients need to be relative to something). What happens is the package will estimate the normalized event study with ` t= -1` set to `0` as usual. Then, it will estimate the mean of the outcome variable in `t = -1` and shift the whole series by that amount. That is, instead of setting `t=-1` to be zero, it sets it to the mean of the outcome in `t=-1`. To highlight that we've mechanically set `t=-1` to it's mean, confidence intervals around that point are still `ommitted`.

**Comment by d0nghyunkang** [comment]
Thanks for the detailed explanation. I learned something!

**Comment by dballaelliott** [comment]
Great! Glad this was helpful! 

I think this is a common source of confusion, so I'll leave this issue open until I can add this information to the package [docs](https://dballaelliott.github.io/esplot/)
