### ISSUE TITLE
[BUG REPORT]: your issue

### ISSUE THREAD

**Issue by dazzler2** [dballaelliott/esplot#18]
I used your example file and entered the command:
esplot paygrade, by(male) event(to_male_mgr) window(-20 30) estimate_reference

I got the following message:
(note:  named style 143 188 187 % 80 not found in class color, default attributes used)
(note:  named style 143 188 187 % 80 not found in class color, default attributes used)
(note:  named style 208 135 112 % 80 not found in class color, default attributes used)
(note:  named style 208 135 112 % 80 not found in class color, default attributes used)

I think this refers to the colors that are supposed to be used for the confidence intervals. The confidence intervals in my plot come out the same color and difficult to distinguish from one another (see screenshot). I am using Stata 14, so it's possible there's an incompatibility? Let me know if that's the issue or if there's something else going on.

<img width="849" alt="image" src="https://user-images.githubusercontent.com/64669169/113771546-7e965c00-96f1-11eb-8896-a448e82dcdf5.png">

**Comment by dballaelliott** [comment]
Hi there, 

I'm fairly confident that this is because the confidence intervals are set to be slightly transparent (that is what the `%80` controls). I think support for transparency was added in Stata 15. Since this does not appear to be governed by the `version` command, it's hard for me to replicate this bug. But, I think I found a workaround. 

I'm going to try patching this by removing the transparency automatically for users with Statas earlier than 15; I'm running the test suite tonight, but I'll try to push this fix to the main branch in the morning (assuming no issues).
